services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --reload"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "local-docker-dev-secret"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    env_file:
      - .env
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A config worker --loglevel=info --concurrency=2
    environment:
      DEBUG: "True"
      SECRET_KEY: "local-docker-dev-secret"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis



  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  media_volume:
