from django.urls import path

from . import views

app_name = "academics"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("dashboard/", views.dashboard, name="dashboard_home"),
    path("student/dashboard/", views.student_dashboard, name="student_dashboard"),
    path("teacher/dashboard/", views.instructor_dashboard, name="instructor_dashboard"),
    path("teacher/courses/", views.teacher_courses, name="teacher_courses"),
    path("teacher/courses/new/", views.create_teacher_course, name="create_teacher_course"),
    path("academic-admin/dashboard/", views.academic_admin_dashboard, name="academic_admin_dashboard"),
    path("platform-admin/dashboard/", views.platform_admin_dashboard, name="platform_admin_dashboard"),
    path("platform-admin/schools/new/", views.create_school, name="create_school"),
    path("platform-admin/schools/<int:school_id>/", views.manage_school, name="manage_school"),
    path("platform-admin/schools/<int:school_id>/edit/", views.edit_school, name="edit_school"),
    path("platform-admin/schools/<int:school_id>/delete/", views.delete_school, name="delete_school"),
    path("platform-admin/schools/<int:school_id>/users/<int:user_id>/remove/", views.remove_user_from_school, name="remove_user_from_school"),
    path("platform-admin/schools/<int:school_id>/users/<int:user_id>/role/", views.change_user_role, name="change_user_role"),
    path("platform-admin/users/new/", views.create_user, name="create_user"),
    path("courses/<slug:slug>/", views.course_detail, name="course_detail"),
    path("courses/<slug:slug>/analytics.pdf", views.course_analytics_pdf, name="course_analytics_pdf"),
    path("courses/<slug:slug>/sections/<int:section_id>/", views.section_detail, name="section_detail"),
    path("materials/<int:material_id>/delete/", views.delete_course_material, name="delete_course_material"),
    path("materials/<int:material_id>/analyze/", views.analyze_material, name="analyze_material"),
    path("ai-tools/request/", views.create_ai_tool_request, name="create_ai_tool_request"),
    path("ai-tasks/", views.ai_tasks_list, name="ai_tasks_list"),
    path("courses/<slug:slug>/ai-generate/", views.ai_generate, name="ai_generate"),
    path("courses/<slug:slug>/lesson-plans/", views.lesson_plan_list, name="lesson_plan_index"),
    path("courses/<slug:slug>/lesson-plans/new/", views.ai_lesson_plan, name="ai_lesson_plan"),
    path("courses/<slug:slug>/lesson-plans/<int:plan_id>/", views.lesson_plan_detail, name="lesson_plan_detail"),
    path("courses/<slug:slug>/lesson-plans/<int:plan_id>/delete/", views.lesson_plan_delete, name="lesson_plan_delete"),
    path("courses/<slug:slug>/activity-sheets/", views.activity_sheet_index, name="activity_sheet_index"),
    path("courses/<slug:slug>/activity-sheets/new/", views.ai_activity_sheets, name="ai_activity_sheets"),
    path("courses/<slug:slug>/activity-sheets/<int:sheet_id>/", views.activity_sheet_detail, name="activity_sheet_detail"),
    path("courses/<slug:slug>/activity-sheets/<int:sheet_id>/delete/", views.activity_sheet_delete, name="activity_sheet_delete"),
    path("courses/<slug:slug>/resources/", views.resource_assistant_index, name="resource_assistant_index"),
    path("courses/<slug:slug>/resources/new/", views.ai_resource_assistant, name="ai_resource_assistant"),
    path("courses/<slug:slug>/resources/manual-add/", views.manual_add_resource, name="manual_add_resource"),
    path("courses/<slug:slug>/resources/<int:session_id>/", views.resource_session_detail, name="resource_session_detail"),
    path("courses/<slug:slug>/resources/<int:session_id>/delete/", views.resource_session_delete, name="resource_session_delete"),
    path("courses/<slug:slug>/resources/<int:session_id>/approve/<int:resource_id>/", views.toggle_resource_approval, name="toggle_resource_approval"),
    path("courses/<slug:slug>/resources/<int:session_id>/reject/<int:resource_id>/", views.toggle_resource_reject, name="toggle_resource_reject"),
    path("courses/<slug:slug>/resources/<int:session_id>/tags/<int:resource_id>/", views.update_resource_tags, name="update_resource_tags"),
    path("courses/<slug:slug>/resources/delete/<int:resource_id>/", views.delete_approved_resource, name="delete_approved_resource"),
    path("courses/<slug:slug>/resources/remove-duplicates/", views.remove_duplicate_resources, name="remove_duplicate_resources"),
    path("courses/<slug:slug>/resources/filters/", views.manage_website_filters, name="manage_website_filters"),
    path("courses/<slug:slug>/resources/filters/<int:filter_id>/delete/", views.delete_website_filter, name="delete_website_filter"),
    path("courses/<slug:slug>/resources/tags/", views.manage_resource_tags, name="manage_resource_tags"),
    path("courses/<slug:slug>/resource-tags/<int:tag_id>/delete/", views.delete_resource_tag, name="delete_resource_tag"),
    path("courses/<slug:slug>/resources/sync-settings/", views.sync_resource_settings, name="sync_resource_settings"),
]
