# Generated by Django 5.2.15 on 2026-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_course_public_id_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="school_year",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus_url",
            field=models.URLField(blank=True),
        ),
    ]
