# Generated by Django 5.2.15 on 2026-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_credits_course_level_course_prerequisites_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="syllabus_url",
        ),
        migrations.AddField(
            model_name="course",
            name="grade_level",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
