# Generated by Django 5.2.15 on 2026-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_course_slug_coursematerial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="category",
            field=models.CharField(
                choices=[
                    ("reading", "Reading Material"),
                    ("lecture", "Lecture Slides/Notes"),
                    ("assignment", "Assignment Resource"),
                    ("syllabus", "Syllabus"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
