# Generated by Django 5.2.15 on 2026-06-16 17:34

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_coursematerial_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="public_id",
            field=models.CharField(
                default=academics.models.generate_short_id,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="public_id",
            field=models.CharField(
                default=academics.models.generate_short_id,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
    ]
