# Generated by Django 5.2.15 on 2026-06-17 17:26

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_course_public_id_alter_coursesection_public_id"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="coursematerial",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("chunk_index", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="academics.coursematerial",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
            },
        ),
    ]
