# Generated by Django 5.2.15 on 2026-06-18 17:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_coursematerial_is_processed_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aitoolrequest',
            name='tool_type',
            field=models.CharField(choices=[('study_plan', 'Study Plan'), ('quiz_generator', 'Quiz Generator'), ('lesson_summary', 'Lesson Summary'), ('feedback_assistant', 'Feedback Assistant'), ('risk_insights', 'Risk Insights'), ('document_analysis', 'Document Analysis')], max_length=40),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.school'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='academics.school'),
        ),
    ]
