# Generated by Django 5.2.15 on 2026-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_school_alter_aitoolrequest_tool_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, help_text='Code for teacher/academic admin self-registration', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(help_text='Code for student self-registration', max_length=64, unique=True),
        ),
    ]
