# Generated by Django 5.2.15 on 2026-06-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_school_teacher_code_alter_school_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, help_text='Code for academic admin self-registration', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, help_text='Code for teacher/instructor self-registration', max_length=64, null=True, unique=True),
        ),
    ]
