# Generated by Django 5.2.15 on 2026-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_generatedlessonplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlessonplan",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedlessonplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="generatedlessonplan",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
