# Generated by Django 5.2.15 on 2026-06-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0015_resourceassistantsession_suggestedresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceassistantsession",
            name="based_on_lesson_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.generatedlessonplan",
            ),
        ),
        migrations.AddField(
            model_name="resourceassistantsession",
            name="based_on_materials",
            field=models.ManyToManyField(blank=True, to="academics.coursematerial"),
        ),
        migrations.AddField(
            model_name="suggestedresource",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ResourceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(blank=True, default="#3b82f6", max_length=20),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_tags",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "name")},
            },
        ),
        migrations.AddField(
            model_name="suggestedresource",
            name="tags",
            field=models.ManyToManyField(blank=True, to="academics.resourcetag"),
        ),
        migrations.CreateModel(
            name="CourseWebsiteFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("trusted", "Trusted"), ("excluded", "Excluded")],
                        max_length=10,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_filters",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "url", "filter_type")},
            },
        ),
    ]
