# Generated by Django 5.2.15 on 2026-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0016_resourceassistantsession_based_on_lesson_plan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="staff_id",
            new_name="id_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="student_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="grade_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
