# Generated by Django 5.2.15 on 2026-06-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0017_rename_staff_id_profile_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("activity", "Activity"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                ],
                default="assignment",
                max_length=20,
            ),
        ),
    ]
