# Generated by Django 5.2.15 on 2026-06-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0018_assignment_activity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["section__order", "order", "due_at", "title"]},
        ),
        migrations.AddField(
            model_name="assignment",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="academics.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="grading_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
