# Generated by Django 5.2.15 on 2026-06-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0019_alter_assignment_options_assignment_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["activity_section__order", "order", "due_at", "title"]
            },
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="section",
        ),
        migrations.RemoveField(
            model_name="coursesection",
            name="grading_weight",
        ),
        migrations.CreateModel(
            name="ActivitySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "grading_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_sections",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order", "name"],
                "unique_together": {("course", "name")},
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="activity_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="academics.activitysection",
            ),
        ),
    ]
