# Generated by Django 5.2.15 on 2026-06-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0020_alter_assignment_options_remove_assignment_section_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": [
                    "activity_section__order",
                    "course_section__order",
                    "order",
                    "due_at",
                    "title",
                ]
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="course_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="academics.coursesection",
            ),
        ),
    ]
