# Generated by Django 5.2.15 on 2026-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0022_assignment_instructor_assignment_time_limit_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
