# Generated by Django 5.2.15 on 2026-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0024_assignment_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_analysis",
            field=models.TextField(blank=True),
        ),
    ]
